/**
 * Better Auth managed tables (Slice 3).
 *
 * The `user` model is NOT here — it maps onto the existing `users` table
 * (`./users.ts`) so there is ONE source of user truth. These are the auxiliary
 * tables Better Auth owns:
 *
 *   - `session`      — server-side sessions in Postgres (revocable: suspend/ban/
 *                      delete drops rows immediately). Token is the bearer value.
 *   - `account`      — credential/social-provider links (OAuth tokens, provider id).
 *   - `verification` — short-lived challenges; the emailOTP + phoneNumber plugins
 *                      store their OTP codes here (identifier+value+expiresAt). No
 *                      extra OTP plugin table is needed — both reuse `verification`.
 *
 * IDs: uuid PKs with gen_random_uuid() default; Better Auth's adapter is told to
 * generate uuids for these models (see services/api auth/generateId), while the
 * `users` row id is generated by Postgres. `user_id` FKs to users(id) ON DELETE
 * CASCADE so deleting a user nukes their sessions/accounts (revocation).
 *
 * Field names are snake_case to match the rest of the schema; the Better Auth
 * adapter is configured with matching `fields` remaps in services/api.
 */
import { index, pgTable, text, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { createdAt, tsTz, updatedAt } from './_shared.js';
import { users } from './users.js';

/** Better Auth `session` — one row per active login; deleting it = logout/revoke. */
export const session = pgTable(
  'session',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    /** Opaque bearer token (also the cookie value). Unique. */
    token: text('token').notNull(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    expiresAt: tsTz('expires_at').notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex('session_token_uq').on(t.token),
    index('session_user_id_idx').on(t.userId),
  ],
);

/** Better Auth `account` — credential rows + linked social providers. */
export const account = pgTable(
  'account',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    /** Provider's user id (or the user id for the credential provider). */
    accountId: text('account_id').notNull(),
    /** 'credential' | 'apple' | 'google' | ... */
    providerId: text('provider_id').notNull(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: tsTz('access_token_expires_at'),
    refreshTokenExpiresAt: tsTz('refresh_token_expires_at'),
    scope: text('scope'),
    /** Hashed password for the credential provider (unused: we are OTP/social-only). */
    password: text('password'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('account_user_id_idx').on(t.userId)],
);

/** Better Auth `verification` — OTP codes + email/phone verification challenges. */
export const verification = pgTable(
  'verification',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    /** e.g. "sign-in-otp-<email>" / phone number / email. */
    identifier: text('identifier').notNull(),
    /** The hashed/plain OTP or token value. */
    value: text('value').notNull(),
    expiresAt: tsTz('expires_at').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('verification_identifier_idx').on(t.identifier)],
);

export type Session = typeof session.$inferSelect;
export type Account = typeof account.$inferSelect;
export type Verification = typeof verification.$inferSelect;
